### ISSUE TITLE
bool operator possible issue

### ISSUE THREAD

**Issue by ShaileshRama** [Tondas/LetsEncrypt#9]
Hi is it possible that this line should have an or instead of an and?

https://github.com/Tondas/LetsEncrypt/blob/b618635c1ef72985c802521de03bfb4da1ef0ca1/Source/LetsEncrypt.Client/BusinessLogic/AcmeClient.Certificate.cs#L19

Regards,
Shailesh Rama

**Comment by Tondas** [comment]
Hi Shailesh, 
yes, you are right, there must be OR ||

**Comment by ShaileshRama** [comment]
i am not sure how to go about fixing it. Is it something I do or is that something you do?

**Comment by Tondas** [comment]
Hi Shailesh,

I have double checked that line of code and it is OK as it is. No change is needed.
